on: [push, pull_request]

name: Build

jobs:
  check:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: update apt
        run: sudo apt update
      - name: install dependencies
        run: sudo apt install -y pkg-config librust-glib-sys-dev librust-atk-sys-dev librust-gdk-sys-dev libasound2-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --color always
